services:
  ProductService:
   image: ${DOCKER_REGISTRY-}producstmicroservice:v1
   build:
    context: C:/Users/Desarroll5/Desktop/MicroserviceProject/ProductMicroservice
    dockerfile: Dockerfile
   environment:
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.31.118,1434;Initial Catalog=microserviceDocker;User ID=sqladmin;Password=Mutombo3000;MultipleActiveResultSets=true;TrustServerCertificate=true
   ports:
    - "4201:80"
  UserService:
   image: ${DOCKER_REGISTRY-}usersmicroservice:v1
   build:
    context: C:/Users/Desarroll5/Desktop/MicroserviceProject/Usermicroservice
    dockerfile: Dockerfile
   environment:
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.31.118,1434;Initial Catalog=microserviceDocker2;User ID=sqladmin;Password=Mutombo3000;MultipleActiveResultSets=true;TrustServerCertificate=true
   ports:
    - "4202:80"